### ISSUE TITLE
SightSense - Helping the visually impaired.

### ISSUE THREAD

**Issue by xditya** [gtech-mulearn/Top100-OpenAi-Challenge#13]
## Problem Identification
We have identified a problem which could help visually impaired people understand their surroundings better.

## Developing
- We have planned on a solution as an Android Application, which uses OpenAI's API, namely [Vision](https://platform.openai.com/docs/guides/vision/vision).
- Our application interprets visual information captured by the device's camera in real time.
- A real world scenario would be a visually impaired person finding himself in an unknown surrounding and using our app to take a quick snapshot of the area and then getting a voice response from our application explaining the captured snapshot.

## Demonstration
- WIP

## Team Members
1. [Aditya](https://github.com/xditya).
2. [Prajwal](https://github.com/prajwalppramod).
3. [Amrithesh](https://github.com/amritheshsiva).

**Comment by xditya** [comment]
issue comment updated, @vishakh-abhayan

**Comment by nhadiq** [comment]
Rejected, No innovation

**Comment by nhadiq** [comment]
Approved
